### ISSUE TITLE
Keep MD5 checksums through pipeline operations

### ISSUE THREAD

**Issue by brainstorm** [UPPMAX/irods#11]
Related to:

https://github.com/SciLifeLab/bcbb/issues/53

All machines the data has been transferred to should keep checksums to trace back possible data corruption/loss.

**Comment by jhagberg** [comment]
Please explain more. 

All machnies? 
iRODS external control script program that keep tracks of md5sum? 

Today checksums is built in in iRODS metadata. And iRODS have control over integrity of files in iRODS name space.

you want wrapper to iget and imetadata that grabs filedata and a md5sum?

**Comment by samuell** [comment]
Just some notes here, FYI: 

We should carefully consider what kind of checksum to use. I think it might be worthwhile considering using adler32 checksums rather than md5sums, since adler32 is what is automatically calculated (and periodically updated) on the Swestore National Storage.

In spite of the bit lesser safety with adler32 as compared to md5sums, we went for this option of the above reason, together with the fact that md5sums take 10 times as long to calculate, increasing the Swestore upload process at least 5 times, which was quite troublesome before.

The efficiency of adler32 varies quite greatly with the size of files, so that should also direct our choice of tar-chunk size, in case we implement the bundling feature in iRODS later. (Right now we went for 20GB chunks, basically since that was the optimum recommended by Swestore, for maximum robustness and upload speed.)

**Comment by brainstorm** [comment]
@jhagberg My idea was more in the line of a typical computer forensics "chain of custody". There should be a simple way to check that the data has not been altered in any of the different transfers it has gone through.

@samuell, unfortunately ichksum (and I would assume iRODs internally) does not seem to support adler32, so we cannot use it right now.

**Comment by brainstorm** [comment]
We shouldn't need to worry about this, I've seen it's pretty well handled on irods itself, by design.

@samuell for simplicity, let's do it with md5 for now, we can explore the adler alternative on next iterations.

**Comment by samuell** [comment]
@brainstorm Yeah, md5 is actually better than adler32. It just takes 10 times more CPU cycles, but it might well be worth it, of course.
