### ISSUE TITLE
Procedure for user .irodsenv file

### ISSUE THREAD

**Issue by jhagberg** [UPPMAX/irods#13]
In this wiki page I am describing the OS auth function of irods.

https://github.com/UPPMAX/irods/wiki/irods-OSauth

When new users are added to irods they should not start by creating a hidden config file themself enabling osAUTh
setting default folder and so on. 

We need to figure out a way to do this automatically and decide where user should be located when first accessing irods. 

Since we do not want an extra home folder. We need to figure out where the users home should be? 

Prmary group? 
A subfolder of all project folder?

**Comment by brainstorm** [comment]
@jhagberg , correct me if I'm wrong, I'm not sure I understood the issue:

Putting a hidden .irods file on a new users folder can be automated by defining it in /etc/skel, the standard UNIX way.

For already created users a simple script that copies .irodsenv files once would be enough.

In addition, by the least surprise principle, keeping the same directory hierarchy on irods would be the way to go, imho.

**Comment by samuell** [comment]
Who is the one that should be assigned these tasks? Let me know if you need help with anything.

**Comment by brainstorm** [comment]
@jhagberg Could you put a typical (or your working one) .irodsEnv file somewhere in the wiki ?

Given your template, we can script it away pretty easily.

**Comment by jhagberg** [comment]
Samuel. 

Can you think how UPPMAX want to present iRODS for their users. 
Should we automate the irodsENV file or should they input the variables when first doing a iinit?

**Comment by brainstorm** [comment]
Guys, as I said, this is just setting up a template on /etc/skel (and/or during the creation of an LDAP user) with reasonable defaults:

<pre>
irodsHost $HOSTNAME
irodsPort 1247
irodsUserName $USER
irodsZone testZone1
</pre>

**Comment by jhagberg** [comment]
Yes it is easy but I don't have the power or mandate to do anything like this on UPPMAX. So Samuel needs to take this to a system meeting and UPPMAX need to decide how to do this. preferable just like you say and copy a default to every user.

**Comment by samuell** [comment]
I have tried the OS Auth now, for the "existing swestore data access" on rot. I guess auto-generated .irodsEnv files should be the way. I'll bring it up on the tuesday meeting next week though ...
(JFYI, they mentioned on the IRODS chat that iinit is actually not needed with OS Auth.)

Regarding home folders, @brainstorm , with "similar directory structure", would that imply that we should have home fodlers on irods as well?

One problem, I guess, is that for our first use case, we mainly want to replace the current Swestore-archiving procedure, which is now done per project ... I'm not sure about the consequences if we let users store personal data on swestore as well ... how much quota could we give etc .... for project data it "feels" easier to just let them store what they need to ..

Also I guess it could make life easier for users if they will see their primary project data when doing an ils, rather than having to go there first with, say:

icd /swestoreArchZone/proj/a2010002

... but there might be different opinions about that? 

One thing is of that it is slightly harder to accidentally damage the project data in irods (accidentally do an irm, or iput -f or sth) if you're located irodswise in your irods home folder rather than the project folder... 

But as said, if having home folders, we need to think hard about the policys for storing personal data on Swestore, for example (or can certain folders be locked to certain storage resources, like the local disk storage only?)

**Comment by brainstorm** [comment]
1) I would just use /proj/a2010002 in swestore.
2) No user "home" folders on swestore, only /proj/a2010002/swestore, not even the whole /proj/a2010002, that gives users the sense that "swestore" is a long storage resource, not just an extension to the parallel filesystem.

In other words, in point 2: Users should not be mirroring the entire /proj, they should just be copying those files that are meant to be long-term stored.

**Comment by samuell** [comment]
I do agree with @brainstorm's two points.

**Comment by samuell** [comment]
I'll have a look at this (adding to skel, and a roll-out script for existing users)

**Comment by jhagberg** [comment]
Can/should this be done by the module system? 

say module load irods

creates or sets user env file for the choosen irodse server. 

module load irods.rot 

sets the right parameters for that server. 

A irods module already exists but can be extended,

**Comment by samuell** [comment]
Now it works with module load irods/rot or and irods/irods1 ... totally without the use of an .irodsEnv file at all ... everything is set up within the module file.

We should probably choose more sensible titles for those? (but right now I use that info as the $host variable :") )

Unfortunetely this will have broke the icommands for u5, but will try to get that up again asap ...

**Comment by jhagberg** [comment]
Great!
Do you mean that icommands on u5 is broken if you load the module file?

**Comment by samuell** [comment]
Yes, since with 
`module load irods`
... you will now load either `irods/rot` or `irods/irods1` :")

**Comment by jhagberg** [comment]
Just broken if loading the module. I can still set the path manually.

**Comment by samuell** [comment]
@jhagberg Yeah, true ... but I guess OS auth does not work for u5, right now, since I updated the icommands to have the keyfile that works on rot and irods1, but let's take that discussion on mail (just mailed you and @brainstorm )
