### ISSUE TITLE
trashbin?

### ISSUE THREAD

**Issue by jhagberg** [UPPMAX/irods#14]
Should we have trashbin or not? 
What is your suggestion?

**Comment by brainstorm** [comment]
From the WTSI paper:

"
With the trashcan function enabled, even when data are removed from iRODS they are still physically located in the storage device. This will lead to an accumulation of redundant data in the disks. Thus, this function should be switched off. This policy could also be configured to periodically empty the trashcan in order to avoid decreasing system responsiveness with deletion requests.
"

I think it's ok if we disable it for now.

**Comment by jhagberg** [comment]
Yes for now when testing we can deactivate it. But should we have a trashbin function or not in the future on the production system? If you delete a file on sweStore it is gone for ever! No DR-backup at all on sweStore. As far as I know.

**Comment by brainstorm** [comment]
Then the periodic strategy would work best, say, flush trashbin every 5-6 months ? Or whatever the storage system allows us to.

**Comment by dahlo** [comment]
If we have snapshots activated on panasas, isn't the trashbin unnecessary?

On second thought, I'm guessing that the files that are checken in in irods
will not change that often. All analysis is carried out outside of irods,
right?

Is is easy to turn the trashbin off if we discover it is too space
consuming?

Mvh
Martin
On Feb 2, 2012 9:25 AM, "jhagberg" <
reply@reply.github.com>
wrote:

**Comment by jhagberg** [comment]
Snapshots will not help file on sweStore.  

It might be possible to do analyses directly with iRODS.

It is easy to turn off trashbin.

**Comment by dahlo** [comment]
If it is easy to turn off, then start with in on. We'll see if it's
possible to keep it.

Mvh

## Martin

m.dahlo@gmail.com
+46 706 70 79 55

On Thu, Feb 2, 2012 at 12:12, jhagberg <
reply@reply.github.com

**Comment by samuell** [comment]
I would like to raise this discussion again. I think being completely without any safety net is too dangerous, since Swestore itself does not have any snapshot like functionality. 

I see the problem with forgotten files in the trash, but I'd suggest adding a rule that cleans files in the trash after 24 or so, thus providing a kind of (short) shapshot system.

**Comment by dahlo** [comment]
I vote in favor of this.

Since the thing with irods is that you can set rules, a simple
cleaning rule should not be impossible to implement (please correct me
if i am wrong). If the trash bin grows beyond our expectations we
should be able to deal with it then by just disabling it.

Mvh

## Martin

m.dahlo@gmail.com
+46 706 70 79 55

On Fri, Apr 27, 2012 at 14:06, Samuel Lampa
reply@reply.github.com
wrote:

**Comment by samuell** [comment]
@jhagberg Do you think you could fix such a rule?

**Comment by jhagberg** [comment]
Yes I need to look in to it but it should be no problems.

**Comment by jhagberg** [comment]
One problem with trashbin... There is no mv function for sweStore... 
If I remove a file on swestore. The operation is to move the file to the trash folder. That is not possible to do with the arc-commands.  One obvious work around is to cope the file to the new place. But that means that you need to download from swestore and than upload again. Perhaps too much overhead.  

rm unixODBC-2.2.12.tar

ERROR: rmUtil: rm error for /testZone1/home/rods/unixODBC-2.2.12.tar, status = -556002 status = -556002 UNIV_MSS_RENAME_ERR, No such file or directory

**Comment by jhagberg** [comment]
We want trash function. 
Workaround is to use the slow srmv command. 
@samuell  need to install this on kali to get it working. 
I will try it out on u5.

**Comment by samuell** [comment]
srmmv command installed.

**Comment by jhagberg** [comment]
We will use trash and as a workaround use the slow Java interface with swestore to move and remove files. This will keep the irods file layout somewhat identically to that of swestore.

**Comment by samuell** [comment]
Trashbin was accidentally turned off, right? ... do you turn it on again @jhagberg ?

**Comment by samuell** [comment]
Closing now, as it is now fixed.
