### ISSUE TITLE
irsync creates replicates on disk but not in iRODS

### ISSUE THREAD

**Issue by jhagberg** [UPPMAX/irods#15]
I have tested irsync and it puts file to sweStore but it also put files on the disk cache. 
But irods thinks that this replica does not exist. 

itrim command dont work. But when trying to iget file it looks like it reads directly from cache and not from sweStore with arc..

**Comment by samuell** [comment]
Yeah, I think the default behaviour of irsync is to sync to all the
resources in one resource group, at least if not specifying the
resource group explicitly with some flags ...

For reading, yes, I suppose this is also the supposed behaviour, to
read directly from cache, at least if the file is there, no? ... and
otherwise download it to cache first, and read it from there?

Or am I missing something?

Btw, what it itrim?

On Tue, Feb 7, 2012 at 12:08 PM, jhagberg
reply@reply.github.com
wrote:

**Comment by jhagberg** [comment]
My bad itrim command works if typing it corectly. (trim -N1 -V -r -S sweStoreCache 9832)
So I always get one replica in cache filesystem when using a compound resource...

We need a rule to look after the cache folder and "trim" replicas...

**Comment by jhagberg** [comment]
Hej I closed this before I read your comment.

I was missguided by the ils output..

an ils -l
give

  rods              0 sweStoreCache             1048576 2012-02-03.13:33 & fef132fd5889e4d4379ee257e8f817e3
  rods              1 sweStore                  1048576 2012-02-03.13:33 & fef132fd5889e4d4379ee257e8f817e3
  rods              0 sweStoreCache               20167 2012-02-03.13:24 & md5sums
  rods              1 sweStore                    20167 2012-02-03.13:24 & md5sums

What does the numbers mean?
I thougt it indicated if you had a replica or not?

This ls means that you have the file both on sweStore and locally on sweStoreCache. 

This is how it looks after itrim.. 
No replica on swestorecache..

ils
  rods              1 sweStore                       64 2012-02-06.15:35 & fe87f94394cad9fdbb22a50d4da3f35d
  rods              1 sweStore                    32768 2012-02-06.15:37 & fe8c752ea0584c6a26baa925b8e1facf
  rods              1 sweStore                    20167 2012-02-06.15:35 & md5sums
