### ISSUE TITLE
Migrate swestore custom chunk structure to iRODS

### ISSUE THREAD

**Issue by brainstorm** [UPPMAX/irods#17]
"ils" should be able to list the datasets as they are stored on swestore today by using a wrapper... or migrate them (by dowloading them and "iputting" them back via irods).

**Comment by jhagberg** [comment]
This should be put on the production system and not the test system.

It should be possible to set up a second zone to handle this read only in the test. The problem is the univMSSdriver and how to handle a second resource with a different driver. 

I can ask Irods list.

**Comment by jhagberg** [comment]
Link to iRODS question
https://groups.google.com/d/msg/irod-chat/w6k_w-pKz9I/wSbEiIxXL2AJ

**Comment by brainstorm** [comment]
Is it possible to register the long term storage objects as "immutable" (readonly) so that we can safely experiment on the test system without risk of overwriting "production" files ?

**Comment by samuell** [comment]
@brainstorm I have in the plans now to try to set up a "read-only" swestore resource on rot, rather than u5. I think that would solve both of the issues we have seen with having it on u5 (disturbint the "sandbox" nature of it, and the problem with multiple univMSS drivers on same machine).

Just has to get the hardware spec, and buy, done first.

**Comment by samuell** [comment]
The rudimentary access to existing Swestore data via rot is now running in alpha test mode. I get it to work for myself, have managed to restrict public access etc, and asked @brainstorm to test it out.

Currently you will only be able to access the chunk-tar files (splitted, where they exceed 20Gb), and need to download and cat/untar them yourself.

It would sure be _possible_ to have some wrapper method in univMSSinterface.sh that would download and stage the tar and split files for you. 

There are some problems though, sucn as that we did not include the size of the individual tar:ed files in the meta files, so that we can not easily implement the "stat" function for those files, which is needed by ireg to register the files in ICAT. Thus one would need to download the data to get correct sizes, and then it's probably better that we go for reprocessing hte data into iRODS own structure instead, as also suggested.

**Comment by jhagberg** [comment]
@pontus Did you have some ideas here? 
I have to many issues on the portal project at the moment that I have hard to find the time.

**Comment by pontus** [comment]
I'll write up something to unpack move it to the new irods then.

**Comment by brainstorm** [comment]
Where is the URL for this documentation?

**Comment by pontus** [comment]
https://www.uppnex.uu.se/faq/how-access-my-old-swestore-data-irods.

There is also a utility called archrest.sh (available after you've done module load irods/swestore_legacy) that helps a littile bit. And data is slowly being copied to the the new swestore structure (as is the original concern of this issue), but it'll take a few months before all is migrated).

**Comment by brainstorm** [comment]
Great, thanks Pontus! :+1:
