### ISSUE TITLE
Rely exlusively on .irodsEnv instead of environment variables

### ISSUE THREAD

**Issue by brainstorm** [UPPMAX/irods#42]
While testing federation with CRS4, I had some issues with iRODS environment variables overriding my custom settings in .irodsEnv, I had to source this script to clear up the env:

<pre>
#!/bin/sh

unset irodsCwd
unset irodsZone
unset irodsAuthScheme
unset irodsPort
unset irodsDefResource
unset irodsUserName
unset irodsHome
unset irodsHost
</pre>

Can you guys please kill the "setenv" commands in the "module load irods"?

**Comment by jhagberg** [comment]
The setenv in module is necessary due to that not every user have the irodsENV file. 
I think this was the best solution for a iRODS module on UPPMAX. Can you confirm this @samuell

**Comment by samuell** [comment]
Yes, that's true. We rely on this method to make this maintainable, but 
even more to allow to easily change between defferent servers. So will 
be able to do e.g:

module unload irods/swestore
module load irods/swestore-legacy

... in order to access the legacy Swestore data (via a separate server), 
without fiddling with .irodsEnv.

But I guess for your use case, you might not need to load the irods 
module at all?

Mvh
// Samuel

**Comment by samuell** [comment]
Closing this issue now, as we rely on this, and AFAIS other use cases has to find workarounds.
