### ISSUE TITLE
Interactive integrity verification tool for files at Swestore

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#49]
Maybe some interactive command to run ... ichksum, or some custom rule that receives the adler32-sum from Swestore and stores in iRODS meta-data? More suggestions?

**Comment by brainstorm** [comment]
I would use ichksum (md5) for all files, even if it takes a more time to compute those, it's already built in and supported.

**Comment by jhagberg** [comment]
Since we force user to use irsync or iput  with the -K
All the checksums are uploaded to irods and stored in irods ICAT. We also use the md5 sum to check the transfer to SWESTORE. 
If a user run ichksum -a all files will be checked against checksum. But I guess it would be safe to delete files as soon as you got OK from irods since then the file is on swestore and has been verified two times.

**Comment by brainstorm** [comment]
+1 on J's arguments.

**Comment by jhagberg** [comment]
If we want to be super safe we need to do a test outside iRODS. So upload files to iRODS and SWESTORE. Trim cache. Iget all the files again and verify with your original md5sums. 

We can perhaps set up some tests and if they look good we can skip it in the future. My first test all worked as planned. But they are dummy files..

**Comment by samuell** [comment]
@jhagberg :s arguments in https://github.com/UPPMAX/irods/issues/49#issuecomment-8522392 sounds reasonable in general. Only I would add that each of the transfer steps actually is only checked only once (not two times), even though it sums up to two checks in total (upload to cache, and upload to Swestore).

**Comment by pontus** [comment]
This is probably due to something that I said that it would be nice for users that don't trust irods to be able to verify file integrity _outside_ of irods. 

That's probably not worth the effort though (given user integrity problems, acls and so on), but I guess Samuel thought it worth to keep some variation of the idea around.

**Comment by samuell** [comment]
I guess we could also just set up some automated tests, that can run periodically (once every day or hour?), so that we identify any problems as soon as they arise. A little python/nose script could do, I guess. (That's something else than a tool for the users themselves to use though ...)

**Comment by brainstorm** [comment]
I think it's overkill, I would rely on iRODS mechanisms (ichksum, -K flag, etc..), i think they should suffice in this regard and there are more pressing issues ATM, I would close this issue and focus on #50 (Samuel, you're awesome in docs ;)) and #18 #38 (Jonas, Pontus & myself if you need some debugging assistance).

**Comment by samuell** [comment]
Ok, thanks for the input @brainstorm . I guess we can wait with this til at least the service release milestone, and await and see if it is actually requested by any users.

**Comment by samuell** [comment]
@pontus has made a script ("ssverify") for this, so closing.
